server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    username: test
    password: 123456
    host: localhost
    virtual-host: /