server:
  port: 31001
spring:
  application:
    name: xc-service-manage-cms
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: xc_cms
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    username: test
    password: 123456
    host: localhost
    virtual-host: /
eureka:
  client:
    register-with-eureka: true #服务注册开关
    fetch-registry: true #服务发现开关
    service-url: #Eureka 客户端与服务端进行交互的地址，多个中间用逗号分割
      defaultZone: http://eureka01:50101/eureka/,http://eureka02:50102/eureka/
  instance:
    prefer-ip-address: true # 将自己的ip地址注册到Eureka服务中
    ip-address: ${IP_ADDRESS:127.0.0.1}
    instance-id: ${spring.application.name}:${server.port}
