server:
  port: 31000
spring:
  application:
    name: xc-service-manage-cms-client
  data:
    mongodb:
      database: xc_cms
      uri: mongodb://localhost
      port: 27017
  rabbitmq:
    host: localhost
    username: test
    password: 123456
    virtual-host: /
    port: 5672
xuecheng:
  mq:
    queue: queue_cms_post_page
    routingKey: 5a751fab6abb5044e0d19ea1